title: Elijah Matthew — Wealth Management Repository
description: Projects, scripts, and notes for wealth management.
theme: minima
header_pages:
  - projects.md
  - scripts.md
  - notes/index.md
  - about.md
