#!/usr/bin/env python3
"""Render the shared bootstrap/launcher templates into each desktop tool.

    python _tools/bootstrap/render.py          # write/refresh the rendered files
    python _tools/bootstrap/render.py --check  # exit 1 if any rendered file is stale

Rendered per project (see projects.toml):
    scripts/bootstrap.py
    Setup_and_Run-<slug>.bat       (CRLF line endings for cmd.exe)
    Setup_and_Run-<slug>.command   (LF line endings, executable)
    config.toml                    ([project], [python], [execution])
"""
from __future__ import annotations

import argparse
import os
import stat
import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
PYTHON_MIN = "3.11"
PYTHON_MAX_EXCLUSIVE = "3.15"


def rendered_files(key: str, spec: dict) -> dict[Path, tuple[bytes, bool]]:
    """Map output path -> (content bytes, executable)."""
    base = ROOT / spec["dir"]
    name = spec["name"]
    bat_name = spec.get("bat_name", name)
    imports = "(" + ", ".join(repr(m) for m in spec["imports"]) + ("," if len(spec["imports"]) == 1 else "") + ")"
    bootstrap = (HERE / "bootstrap.py.in").read_text(encoding="utf-8")
    bootstrap = bootstrap.replace("@@PROJECT_NAME@@", name).replace("@@REQUIRED_IMPORTS@@", imports)
    bat = (HERE / "Setup_and_Run.bat.in").read_text(encoding="utf-8").replace("@@BAT_NAME@@", bat_name)
    command = (HERE / "Setup_and_Run.command.in").read_text(encoding="utf-8").replace("@@PROJECT_NAME@@", name)
    config = (
        f"# {name} settings read by scripts/bootstrap.py.\n"
        "# Generated by _tools/bootstrap/render.py in the website repository.\n\n"
        "[project]\n"
        f'name = "{name}"\n'
        f'version = "{spec["version"]}"\n'
        'profile = "python-desktop"\n'
        'platforms = ["windows", "macos"]\n\n'
        "[python]\n"
        f'minimum_version = "{PYTHON_MIN}"\n'
        f'maximum_version_exclusive = "{PYTHON_MAX_EXCLUSIVE}"\n\n'
        "[execution]\n"
        f'entry_point = "{spec["entry_point"]}"\n'
    )
    for text in (bootstrap, bat, command):
        if "@@" in text:
            raise SystemExit(f"{key}: unresolved template placeholder")
    return {
        base / "scripts" / "bootstrap.py": (bootstrap.encode("utf-8"), False),
        base / f"Setup_and_Run-{spec['slug']}.bat": (bat.replace("\r\n", "\n").replace("\n", "\r\n").encode("ascii"), False),
        base / f"Setup_and_Run-{spec['slug']}.command": (command.replace("\r\n", "\n").encode("utf-8"), True),
        base / "config.toml": (config.encode("utf-8"), False),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify only; do not write")
    args = parser.parse_args()
    projects = tomllib.loads((HERE / "projects.toml").read_text(encoding="utf-8"))
    stale = []
    for key, spec in projects.items():
        for path, (content, executable) in rendered_files(key, spec).items():
            current = path.read_bytes() if path.is_file() else None
            exec_ok = not executable or os.name == "nt" or (path.is_file() and path.stat().st_mode & stat.S_IXUSR)
            if current == content and exec_ok:
                continue
            if args.check:
                stale.append(path.relative_to(ROOT).as_posix())
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
            if executable:
                path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            print(f"wrote {path.relative_to(ROOT).as_posix()}")
    if stale:
        print("Stale rendered files (run _tools/bootstrap/render.py):\n  " + "\n  ".join(stale))
        return 1
    if args.check:
        print("All rendered bootstrap files are current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
